name: apik_mobile
description: APIK Corporation Mobile App for Customers
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # State Management
  flutter_riverpod: ^2.5.1
  riverpod_annotation: ^2.3.5

  # Routing
  go_router: ^14.2.0

  # Local Storage
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  shared_preferences: ^2.2.3

  # Network & API
  dio: ^5.4.3
  pretty_dio_logger: ^1.3.1
  connectivity_plus: ^6.0.3

  # UI Components
  flutter_svg: ^2.0.10
  cached_network_image: ^3.3.1
  shimmer: ^3.0.0
  flutter_spinkit: ^5.2.1
  google_fonts: ^6.1.0
  cupertino_icons: ^1.0.6
  font_awesome_flutter: 10.7.0
  fluttertoast: ^8.2.4

  # Utils
  intl: ^0.19.0
  url_launcher: ^6.3.0
  image_picker: ^1.0.7
  http: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  build_runner: ^2.4.11
  riverpod_generator: ^2.4.0
  hive_generator: ^2.0.1
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true

  assets:
    - assets/icon/
    - assets/images/
    - assets/icons/

flutter_launcher_icons:
  android: "launcher_icon"
  ios: false
  image_path: "assets/icon/app_icon.png"
  min_sdk_android: 21
  adaptive_icon_background: "#FFFFFF"
  web:
    generate: true
    image_path: "assets/icon/app_icon.png"
    background_color: "#FFFFFF"
    theme_color: "#6A5ACD"

